Fix compatibility with boost 1.56+
In boost 1.56 the optional library is no longer happy with the implicit
conversion from boost::optional<std::string> to bool, so we get the following
errors:

    valijson/include/valijson/schema.hpp:177:16: error: no viable conversion from 'const boost::optional<std::string>' to 'bool'
            return id;
                   ^~

    valijson/include/valijson/schema.hpp:188:16: error: no viable conversion from 'const boost::optional<std::string>' to 'bool'
                    return title;
                           ^~~~~
    2 errors generated.

Here we explicitly test against boost::none instead.